CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE products (
    id VARCHAR(255) PRIMARY KEY,
    sku VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    reorder_point INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT ck_products_price_nonnegative CHECK (price >= 0),
    CONSTRAINT ck_products_reorder_point_nonnegative CHECK (reorder_point >= 0)
);

CREATE TABLE suppliers (
    id VARCHAR(255) PRIMARY KEY,
    supplier_code VARCHAR(128) NOT NULL,
    name VARCHAR(200) NOT NULL,
    contact_email VARCHAR(254),
    phone VARCHAR(32),
    lead_time_days INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_suppliers_supplier_code UNIQUE (supplier_code),
    CONSTRAINT ck_suppliers_lead_time_days CHECK (lead_time_days BETWEEN 0 AND 3650)
);

CREATE TABLE warehouses (
    id VARCHAR(255) PRIMARY KEY,
    warehouse_code VARCHAR(128) NOT NULL,
    name VARCHAR(200) NOT NULL,
    location VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_warehouses_warehouse_code UNIQUE (warehouse_code)
);

CREATE TABLE orders (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    warehouse_id VARCHAR(255) NOT NULL,
    status VARCHAR(24) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE,
    shipped_at TIMESTAMP WITH TIME ZONE,
    expired_at TIMESTAMP WITH TIME ZONE,
    payment_reference VARCHAR(64),
    version BIGINT NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_orders_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_orders_status CHECK (status IN ('RESERVED', 'PAID', 'SHIPPED', 'CANCELLED', 'EXPIRED'))
);

CREATE TABLE order_items (
    id VARCHAR(255) PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    quantity BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    line_total NUMERIC(19, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT uk_order_items_order_line_number UNIQUE (order_id, line_number),
    CONSTRAINT ck_order_items_line_number_positive CHECK (line_number > 0),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0)
);

CREATE TABLE inventories (
    id VARCHAR(255) PRIMARY KEY,
    product_id VARCHAR(255) NOT NULL,
    warehouse_id VARCHAR(255) NOT NULL,
    on_hand BIGINT NOT NULL,
    reserved BIGINT NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_inventories_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_inventories_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT uk_inventories_product_warehouse UNIQUE (product_id, warehouse_id),
    CONSTRAINT ck_inventories_quantities CHECK (on_hand >= 0 AND reserved >= 0 AND reserved <= on_hand)
);

CREATE TABLE inventory_movements (
    id VARCHAR(255) PRIMARY KEY,
    inventory_id VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    warehouse_id VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL,
    on_hand_delta BIGINT NOT NULL,
    reserved_delta BIGINT NOT NULL,
    on_hand_before BIGINT NOT NULL,
    on_hand_after BIGINT NOT NULL,
    reserved_before BIGINT NOT NULL,
    reserved_after BIGINT NOT NULL,
    reference VARCHAR(256),
    reason VARCHAR(1000),
    created_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_inventory_movements_inventory FOREIGN KEY (inventory_id) REFERENCES inventories (id),
    CONSTRAINT fk_inventory_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_inventory_movements_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_inventory_movements_type CHECK (type IN ('INITIAL_STOCK', 'RECEIPT', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'RESERVATION', 'RELEASE', 'SHIPMENT'))
);

CREATE INDEX ix_orders_user_id ON orders (user_id);
CREATE INDEX ix_orders_warehouse_id ON orders (warehouse_id);
CREATE INDEX ix_orders_expiration ON orders (status, expires_at, id);
CREATE INDEX ix_order_items_order_id ON order_items (order_id);
CREATE INDEX ix_order_items_product_id ON order_items (product_id);
CREATE INDEX ix_inventory_movements_inventory_created ON inventory_movements (inventory_id, created_at, id);
