spring:
  application:
    name: stockflow-api
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
    baseline-on-migrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000
  order-expiration:
    enabled: true
    interval-ms: 60000
    batch-size: 100

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
